enum provinces {
  Azua = "Azua",
  Bahoruco = "Bahoruco",
  Barahona = "Barahona",
  Dajabón = "Dajabón",
  Distrito_Nacional = "Distrito Nacional",
  Duarte = "Duarte",
  Elías_Piña = "Elías Piña",
  El_Seibo = "El Seibo",
  Espaillat = "Espaillat",
  Hato_Mayor = "Hato Mayor",
  Hermanas_Mirabal = " Hermanas Mirabal",
  Independencia = "Independencia",
  La_Altagracia = "La Altagracia",
  La_Romana = "La Romana:",
  La_Vega = "La Vega",
  María_Trinidad_Sánchez = "María Trinidad Sánchez",
  Monseñor_Nouel = "Monseñor Nouel",
  Monte_Cristi = "Monte Cristi",
  Monte_Plata = "Monte Plata",
  Pedernales = "Pedernales",
  Peravia = "Peravia",
  Puerto_Plata = "Puerto Plata",
  Samaná = "Samaná",
  San_Cristóbal = "San Cristóbal",
  San_José_de_Ocoa = "San José de Ocoa",
  San_Juan = "San Juan",
  San_Pedro_de_Macorís = "San Pedro de Macorís",
  Sánchez_Ramírez = "Sánchez Ramírez",
  Santiago = "Santiago",
  Santiago_Rodríguez = "Santiago Rodríguez",
  Santo_Domingo = "Santo Domingo",
  Valverde = "Valverde",
}

export default provinces;
